import mongoose from 'mongoose';
import { CHAT_INTENTS, YES_NO_EMPTY } from '../constants/validationEnums.js';
const leadProfileSchema = new mongoose.Schema(
  {
    intent: {
      type: String,
      enum: CHAT_INTENTS,
      required: true,
    },
    full_name: { type: String },
    email: { type: String },
    phone: { type: String },
    property_address: { type: String },
    location: { type: String },
    budget: { type: String },
    expected_price: { type: String },
    timeline: { type: String },
    bedrooms: { type: String },
    bathrooms: { type: String },
    square_footage: { type: String },
    property_type: { type: String },
    must_have_features: { type: String },
    parking_required: { type: String, enum: YES_NO_EMPTY, default: '' },
    backyard_needed: { type: String, enum: YES_NO_EMPTY, default: '' },
    school_district_important: { type: String, enum: YES_NO_EMPTY, default: '' },
    preferred_contact_method: { type: String },
    best_time_to_contact: { type: String },
    mortgage_status: { type: String },
    realtor_status: { type: String },
    motivation_reason: { type: String },
    viewing_readiness: { type: String },
    living_situation: { type: String },
    urgency_readiness: { type: String },
    mortgage_timeline: { type: String },
    transaction_stage: { type: String },
    closing_timeline: { type: String },
    transaction_type: { type: String },
    property_value: { type: String },
    realtor_involved: { type: String },
    first_time_buyer: { type: String },
    legal_services_needed: { type: String },
    pre_approval_status: { type: String },
    credit_score_range: { type: String },
    employment_status: { type: String },
    household_income: { type: String },
    down_payment_readiness: { type: String },
    purchase_purpose: { type: String },
    urgency_signal: { type: String },
    mortgage_property_budget: { type: String },
    source: { type: String, default: 'chatbot' },
    total_score: { type: Number, default: 0 },
  },
  { timestamps: true }
);
export default mongoose.model('LeadProfile', leadProfileSchema);
