import mongoose from 'mongoose';
import { CHAT_INTENTS, YES_NO_EMPTY } from '../constants/validationEnums.js';
import { PROFESSIONAL_TYPE, PROFESSIONAL_TYPE_VALUES } from '../constants/roles.js';
const leadProfileSchema = new mongoose.Schema(
  {
    intent: { type: String, enum: CHAT_INTENTS, required: true, index: true },
    ownership: {
      user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
      professional_type: {
        type: String,
        enum: PROFESSIONAL_TYPE_VALUES,
        default: PROFESSIONAL_TYPE.AGENT,
        index: true,
      },
      dedupe_key: { type: String, index: true },
    },
    identity: {
      full_name: { type: String },
      email: { type: String },
      phone: { type: String },
      canonical_email: { type: String, index: true },
      canonical_phone: { type: String, index: true },
    },
    lifecycle: {
      status: { type: String, default: 'new' },
      first_seen_at: { type: Date, default: Date.now },
      last_seen_at: { type: Date, default: Date.now },
      last_inquiry_at: { type: Date, default: Date.now },
    },
    intent_summary: {
      primary_intent: { type: String, enum: ['buy', 'sell', 'client', 'unknown'], default: 'unknown' },
      buy_count: { type: Number, default: 0 },
      sell_count: { type: Number, default: 0 },
      client_count: { type: Number, default: 0 },
    },
    budget_profile: {
      latest_budget_text: { type: String, default: '' },
      min_budget: { type: Number, default: null },
      max_budget: { type: Number, default: null },
      currency: { type: String, default: '' },
      confidence: { type: String, enum: ['low', 'medium', 'high'], default: 'low' },
    },
    contact_preferences: {
      preferred_contact_method: { type: String },
      best_time_to_contact: { type: String },
    },
    property: {
      address: { type: String },
      location: { type: String },
      budget: { type: String },
      expected_price: { type: String },
      timeline: { type: String },
      bedrooms: { type: String },
      bathrooms: { type: String },
      square_footage: { type: String },
      property_type: { type: String },
      must_have_features: { type: String },
      parking_required: { type: String, enum: YES_NO_EMPTY, default: '' },
      backyard_needed: { type: String, enum: YES_NO_EMPTY, default: '' },
      school_district_important: { type: String, enum: YES_NO_EMPTY, default: '' },
    },
    qualification: {
      agent: {
        mortgage_status: { type: String },
        realtor_status: { type: String },
        motivation_reason: { type: String },
        viewing_readiness: { type: String },
        living_situation: { type: String },
        urgency_readiness: { type: String },
      },
      mortgage_broker: {
        mortgage_timeline: { type: String },
        pre_approval_status: { type: String },
        credit_score_range: { type: String },
        employment_status: { type: String },
        household_income: { type: String },
        down_payment_readiness: { type: String },
        purchase_purpose: { type: String },
        urgency_signal: { type: String },
        property_budget: { type: String },
      },
      lawyer: {
        transaction_stage: { type: String },
        closing_timeline: { type: String },
        transaction_type: { type: String },
        property_value: { type: String },
        mortgage_status: { type: String },
        realtor_involved: { type: String },
        first_time_buyer: { type: String },
        legal_services_needed: { type: String },
      },
    },
    scoring: {
      current_score: { type: Number, default: 0 },
      current_grade: { type: String, default: 'unscored' },
      score_trend: { type: String, enum: ['up', 'down', 'stable'], default: 'stable' },
      last_scored_at: { type: Date, default: Date.now },
      components: { type: mongoose.Schema.Types.Mixed, default: {} },
    },
    source: { type: String, default: 'chatbot' },
    total_score: { type: Number, default: 0 },
    stats: {
      total_inquiries: { type: Number, default: 0 },
      total_sessions: { type: Number, default: 0 },
      total_matches: { type: Number, default: 0 },
      buy_matches: { type: Number, default: 0 },
      sell_matches: { type: Number, default: 0 },
      client_matches: { type: Number, default: 0 },
      last_seen_at: { type: Date, default: Date.now },
    },
    lead_refs: [{ type: mongoose.Schema.Types.ObjectId, ref: 'LeadMatch' }],
  },
  { timestamps: true }
);
export default mongoose.model('LeadProfile', leadProfileSchema);
